### ISSUE TITLE
数据填充报错

### ISSUE THREAD

**Issue by cbjason** [github-muzilong/laravel55-layuiadmin#1]
file_get_contents(/home/vagrant/code/admin/layui_admin/storage/app\public\icons.json): failed to open stream: No such file or directory

**Comment by yangchangdong** [comment]
使用php artisan db:seed时报错：
/laravel55-layuiadmin-master/storage/app\public\icons.json): failed to open stream: No such file or directory 
修改文件
laravel55-layuiadmin-master/database/seeds/IconTableSeeder.php中的15行
`$file = file_get_contents(storage_path('app').'\public\icons.json');`

改成
`$file = file_get_contents(storage_path('app').'/public/icons.json');`
